### ISSUE TITLE
Missing headers, make targets

### ISSUE THREAD

**Issue by static-void** [ColumPaget/ParanoidTelnetD#1]
I tried to build this. It seems to be missing some headers (ansi.h, openssl.h). Then the libUseful makefile also tries to build a bunch of targets that are missing (ansi.o, openssl.o, whirlpool.o, jh_ref.o). If you remove these targets from the makefile it then fails to build Hash.o, and of course finally these missing dependencies mean the whole lot wont link. Seems like it could be a useful tool if I could get it going...

**Comment by ColumPaget** [comment]
wow, that's odd. I must've messed up a commit at some point.

I'll look into this tonight, and upload a new version.

Colum

**Comment by ColumPaget** [comment]
I'm afraid it's taken me a long time to find a timeslot to look into this, but the latest version should now fix this issue.

**Comment by static-void** [comment]
Thanks!
